---
- name: Install X packages
  become: yes
  community.general.pacman:
    name:
      - xorg-server
      - xorg-xinput
      - xorg-xev
- name: Copy file for monitor info
  become: yes
  ansible.builtin.copy:
    src: 90-monitor.conf
    dest: /etc/X11/xorg.conf.d/90-monitor.conf
- name: Copy file for touchpad tapping click
  become: yes
  ansible.builtin.copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
