---
- name: Install tmux (pacman)
  become: yes
  community.general.pacman:
    name: tmux
    state: latest
  when: ansible_facts['distribution'] == "ArchLinux"
- name: Install tmux (apt)
  become: yes
  ansible.builtin.apt:
    name: tmux
    state: latest
    force_apt_get: yes
  when: ansible_facts['distribution'] == "Ubuntu"
- name: Install xclip for copy/paste (pacman)
  become: yes
  community.general.pacman:
    name: xclip
    state: latest
  when: ansible_facts['distribution'] == "ArchLinux"
- name: Install xclip for copy/paste (apt)
  become: yes
  ansible.builtin.apt:
    name: xclip
    state: latest
    force_apt_get: yes
  when: ansible_facts['distribution'] == "Ubuntu"
- name: Copy/update tmux configuration file
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
- name: Clone tpm repo for plugin management
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
- name: Copy/update tmux configuration directory
  ansible.builtin.copy:
    src: tmux/
    dest: "{{ config_home }}/tmux/"
- name: Copy/update tmux init file
  ansible.builtin.template:
    src: init.tmux.conf.j2
    dest: "{{ config_home }}/tmux/init.tmux.conf"
