---
- name: Install yay
  hosts: localhost
  tasks:
    - name: Install graphics packages
      become: yes
      community.general.pacman:
        name:
          - nvidia
          - nvidia-utils
        state: latest
