# This file simply sources the configuration file pointed to at
# $XDG_CONFIG_HOME/zsh/init.zsh.

if [ -z ${XDG_CONFIG_HOME+x} ]; then
	export XDG_CONFIG_HOME=$HOME/.config
fi
export ZSH_CONFIG=$XDG_CONFIG_HOME/zsh
source $ZSH_CONFIG/init.zsh

# STOP. DO NOT ADD ANYTHING TO THIS FILE. Change the init.zsh file instead.
